Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "smtp-server"
    config.vm.network "forwarded_port", guest: 25, host:25

    # Configure hardware resources for VM
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
    end

    # Run provisioning script
    config.vm.provision "shell", path: "provision_smtp.sh"
end